apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: integrations.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: Integration
    listKind: IntegrationList
    plural: integrations
    singular: integration
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            serviceProvider:
              type: string
            integrationType:
              type: string
            client:
              type: string
            enabled:
              type: boolean
            metaData:
              type: object
