apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integration-editor
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - integreatly.org
  resources:
  - 'integrations'
  verbs:
  - 'update'
  - 'patch'
  - 'get'
  - 'list'