apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: integration-controller
  template:
    metadata:
      labels:
        name: integration-controller
    spec:
      containers:
        - name: integration-controller
          image: quay.io/integreatly/integration-controller:0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - integration-controller
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "integration-controller"
