apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  name: route-service-viewer
rules:
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get","list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","list","watch"]