apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enmasse-integration-viewer
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["keycloak-credentials"] #needed until we can add a user via CR
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get"]
  resourceNames: ["keycloak"] #needed until we can add a user via CR


