apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  generateName: integration-controller-enmasse-view-
  namespace: enmasse
  labels:
    for: integration-controller
roleRef:
  name: enmasse-integration-viewer
subjects:
- kind: ServiceAccount
  name: integration-controller
  namespace: FUSE_NAMESPACE # needs to be set at deploy
userNames:
- system:serviceaccount:FUSE_NAMESPACE:integration-controller #needs to be set at deploy
